apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.35-5-alpine
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    serviceAccount: jenkins-operator-todo
    serviceAccountName: jenkins-operator-todo
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.15.0
    command:
    - /busybox/cat
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    tty: true
    volumeMounts:
    - name: registry-cred
      mountPath: /kaniko/.docker/
  volumes:
    - name: registry-cred
      secret:
        secretName: registry-cred
        items:
          - key: .dockerconfigjson
            path: config.json
  restartPolicy: Never