apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
spec:
  rules:
  - host: jenkins.hari-karthigasu.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-operator-http-titanic
          servicePort: 8080
