apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo
  name: todo
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - image: harikarthi/todo:latest
        name: todo
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m
        envFrom:
        - configMapRef:
            name: todo-conf
        - secretRef:
            name: mongo-cred
status: {}
